### ISSUE TITLE
Which freeCappuccino version do you recommend to use?

### ISSUE THREAD

**Issue by cesss** [nikola-m/freeCappuccino-dev#1]
I saw that you have several repositories for your freeCappuccino code. I wish to try it for simulating 3D natural convection of incompressible air in unsteady flow (Boussinesq approximation), but also having an inlet with known airspeed and an outlet. Do you think your code will work fine for this kind of simulation? Which of the repositories would you suggest to use?

**Comment by nikola-m** [comment]
I'm restructuring the code a lot now, so this dev variant is most up to
date. I have new version which differs in some way and I would like to
suggest its use.  Let me just push the  freshest version tommorrow to dev
repo and I will be happy to help you to get started with the code in
general and with your specidic problem.

In new version there is new way we configure simulation using namelist
which is a forttan dictionary, and I would like you to start with it.

Best regards,
Nikola

**Comment by cesss** [comment]
That would be great, Nikola! I've been searching for weeks some code that implements PISO in 3D  (with temperature) but with the requirement of not being as complex as OpenFOAM, and your code seems to be the best candidate I found! And that namelist feature for configuration looks like a very interesting feature.

**Comment by cesss** [comment]
By the way, my air flow is turbulent, although I didn't mention because I believe the effects of turbulence in this simulation won't be important, but it's a plus that you have several turbulence models implemented, because I'll be able to compare results between considering turbulence and ignoring it, and between different turbulence models.

**Comment by nikola-m** [comment]
Contact me directly through my email: largeddysimulation@gmail.com (copy
paste it - it has one 'e' missing), and we'll go from there.

In fCp both SIMPLE and PISO are good for unsteady flows. The distinction
made here is that in SIMPLE we solve the pressure correction equation, and
for PISO we solve for pressure directly, so people can see both things.

I have plan to make videos to help people to get started, there's a lot of
work, but this is the year when the code needs to get wings.

**Comment by nikola-m** [comment]
Ok before I close the issue let me give definitive answer.

I recommend using (this) freeCappuccino-dev repositorium. The code is in constant development because we have a lot of work to do to catch up with others, and this is the place to keep an eye on.
